### PR TITLE
Remove class nesting

### PR DESCRIPTION
**Pull request by mjp41**
Nesting the class inside a function generates bad code in Debug (#584). Unnesting seems to fix this.

### CODE REVIEW

**Comment by mjp41** [comment]
So this almost halves the time taken in `./perf-singlethread-fast` in Debug.  

Before PR:
```
Count:  32768, Size:     16, ZeroMem: 1, Write: 1:    710732132 ns
```
After this PR:
```
Count:  32768, Size:     16, ZeroMem: 1, Write: 1:    402341898 ns
```

There also seems to be an improvement on time for Release.  I am going to investigate this more deeply.

**Comment by mjp41** [comment]
The issues seems to be dependent on the version of Clang.  On Clang-10, I had slow downs, but not on Clang-12.

**Comment by mjp41** [comment]
I propose taking this refactoring.

**Comment by nwf** [comment]
Hrm.  It LGTM but the cluster CI seems to be acting up.  I'll look when I get a minute or when I get back.

**Pull request merged**
