### PR TITLE
Reordering pal_noalloc due to the memset call in. caught with solaris…

### PR DESCRIPTION
**Pull request by devnexen**
… build.

### CODE REVIEW

**Comment by mjp41** [comment]
Thanks for spotting this.  I would prefer to fix this by adding 
```
#include <cstring>
```
to `pal_noalloc.h`.  That file needs `memset`.  Forcing clangformat to include in the right order always seems a little wrong to me.

@davidchisnall,  do you have a preference here?

**Comment by devnexen** [comment]
I thought doing this primarly but I thought it was not there for a reason.

**Comment by mjp41** [comment]
Hence, why I pinged @davidchisnall :-)

**Comment by devnexen** [comment]
We can eventually as third alternative rename to pal_zeroalloc.h :-)

**Comment by mjp41** [comment]
LOL

**Comment by davidchisnall** [comment]
I prefer headers to include everything that they need and have working guards against multiple inclusion.  I obviously failed here, sorry!

**Review by mjp41 — APPROVED** [review]

**Pull request merged**
