### PR TITLE
Fix for #506

### LINKED ISSUE #506: Bug: Linking Chromium with lld-link using snmalloc fails
Hello!

I'm seeing a failure while trying to link Chromium's `unit_tests.exe` on Windows. I am using a custom-built two-stage `lld-link.exe` that uses snmalloc. The error is: "out of memory: 0x25cfc000000 (0x4000000) could not be committed (0x1e7)". The last error code, ie. 0x1e7, translates to "**ERROR_INVALID_ADDRESS**". The [documentation](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc) mentions that such error is thrown when attempting to commit a memory range that is not reserved -- _see VMMap snapshot below_.

The callstack is:
```
D:\git\chromium\src\out\Default>D:\git\llvm-project\stage2_snmalloc\bin\lld-link.exe @__link.rsp /summary /time
out of memory: 0x2a27c000000 (0x4000000) could not be committed (0x1e7)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: D:\\git\\llvm-project\\stage2_snmalloc\\bin\\lld-link.exe @__link.rsp /summary /time
 #0 0x00007ff66179bf56 HandleAbort D:\git\llvm-project\llvm\lib\Support\Windows\Signals.inc:418:0
 #1 0x00007ff664c26a1f raise D:\git\llvm-project\stage2_snmalloc\minkernel\crts\ucrt\src\appcrt\misc\signal.cpp:547:0
 #2 0x00007ff664c1d83c abort D:\git\llvm-project\stage2_snmalloc\minkernel\crts\ucrt\src\appcrt\startup\abort.cpp:71:0
 #3 0x00007ff6616daf1e snmalloc::PALWindows::error(char const *const) D:\git\snmalloc\src\snmalloc\pal\pal_windows.h:128:0
 #4 0x00007ff6616daf0b snmalloc::report_fatal_error<1024, char const *, void *, unsigned __int64, unsigned long>(char const *, void *, unsigned __int64, unsigned long) D:\git\snmalloc\src\snmalloc\pal\pal.h:180:0
 #5 0x00007ff6616dc386 snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0>::dealloc_overflow D:\git\snmalloc\src\snmalloc\backend_helpers\largebuddyrange.h:210:0
 #6 0x00007ff6616dc386 snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0>::add_range::<lambda_1>::operator() D:\git\snmalloc\src\snmalloc\backend_helpers\largebuddyrange.h:242:0
 #7 0x00007ff6616dc386 snmalloc::range_to_pow_2_blocks D:\git\snmalloc\src\snmalloc\backend_helpers\range_helpers.h:30:0
 #8 0x00007ff6616dc386 snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0>::add_range D:\git\snmalloc\src\snmalloc\backend_helpers\largebuddyrange.h:220:0
 #9 0x00007ff6616dc386 snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0>::refill D:\git\snmalloc\src\snmalloc\backend_helpers\largebuddyrange.h:258:0
#10 0x00007ff6616dc386 snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0>::alloc_range D:\git\snmalloc\src\snmalloc\backend_helpers\largebuddyrange.h:333:0
#11 0x00007ff6616dc386 snmalloc::StatsRange<snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0> >::alloc_range D:\git\snmalloc\src\snmalloc\backend_helpers\statsrange.h:40:0
#12 0x00007ff6616dc386 snmalloc::GlobalRange<snmalloc::StatsRange<snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0> > >::alloc_range D:\git\snmalloc\src\snmalloc\backend_helpers\globalrange.h:45:0
#13 0x00007ff6616dc386 snmalloc::CommitRange<snmalloc::GlobalRange<snmalloc::StatsRange<snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0> > >,snmalloc::PALWindows>::alloc_range D:\git\snmalloc\src\snmalloc\backend_helpers\commitrange.h:37:0
#14 0x00007ff6616dbe4c snmalloc::LargeBuddyRange<snmalloc::CommitRange<snmalloc::GlobalRange<snmalloc::StatsRange<snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0> > >,snmalloc::PALWindows>,21,21,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,1>::alloc_range D:\git\snmalloc\src\snmalloc\backend_helpers\largebuddyrange.h:333:0
#15 0x00007ff6616dbe4c snmalloc::SmallBuddyRange<snmalloc::LargeBuddyRange<snmalloc::CommitRange<snmalloc::GlobalRange<snmalloc::StatsRange<snmalloc::LargeBuddyRange<snmalloc::PagemapRegisterRange<snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,snmalloc::PalRange<snmalloc::PALWindows> >,24,63,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,0> > >,snmalloc::PALWindows>,21,21,snmalloc::BackendAllocator<snmalloc::PALWindows,0>::Pagemap,1> >::alloc_range D:\git\snmalloc\src\snmalloc\backend_helpers\smallbuddyrange.h:206:0
#16 0x00007ff6616dbe4c snmalloc::BackendAllocator<snmalloc::PALWindows,0>::alloc_chunk D:\git\snmalloc\src\snmalloc\backend\backend.h:312:0
#17 0x00007ff6616db46a snmalloc::LocalAllocator<snmalloc::Globals>::alloc_not_small<0>::<lambda_1>::operator() D:\git\snmalloc\src\snmalloc\mem\localalloc.h:208:0
#18 0x00007ff6616db46a snmalloc::CoreAllocator<snmalloc::Globals>::handle_message_queue D:\git\snmalloc\src\snmalloc\mem\corealloc.h:668:0
#19 0x00007ff6616db46a snmalloc::LocalAllocator<snmalloc::Globals>::check_init D:\git\snmalloc\src\snmalloc\mem\localalloc.h:106:0
#20 0x00007ff6616db46a snmalloc::LocalAllocator<class snmalloc::Globals>::alloc_not_small<0>(unsigned __int64) D:\git\snmalloc\src\snmalloc\mem\localalloc.h:184:0
#21 0x00007ff6616da519 snmalloc::LocalAllocator<snmalloc::Globals>::alloc D:\git\snmalloc\src\snmalloc\mem\localalloc.h:442:0
#22 0x00007ff6616da519 malloc D:\git\snmalloc\src\snmalloc\override\new.cc:28:0
#23 0x00007ff6617fbb82 std::_Allocate_manually_vector_aligned C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory:143:0
#24 0x00007ff6617fbb82 std::_Allocate C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory:238:0
#25 0x00007ff6617fbb82 std::allocator<lld::coff::Chunk *>::allocate C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory:839:0
#26 0x00007ff6617fbb82 std::vector<class llvm::Type *, class std::allocator<class llvm::Type *>>::_Insert_range<class llvm::Type *const *>(class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types<class llvm::Type *>>>, class llvm::Type *const *, class llvm::Type *const *, struct std::forward_iterator_tag) C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector:973:0
#27 0x00007ff661855ec1 std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<lld::coff::ObjFile *> > >::operator++ C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector:78:0
#28 0x00007ff661855ec1 std::_Vector_iterator<std::_Vector_val<std::_Simple_types<lld::coff::ObjFile *> > >::operator++ C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector:284:0
#29 0x00007ff661855ec1 lld::coff::SymbolTable::getChunks D:\git\llvm-project\lld\COFF\SymbolTable.cpp:806:0
#30 0x00007ff661855ec1 `anonymous namespace'::Writer::createSections D:\git\llvm-project\lld\COFF\Writer.cpp:863:0
#31 0x00007ff661855ec1 `anonymous namespace'::Writer::run D:\git\llvm-project\lld\COFF\Writer.cpp:608:0
#32 0x00007ff6618543f1 std::vector<std::pair<llvm::COFF::DebugType,lld::coff::Chunk *>,std::allocator<std::pair<llvm::COFF::DebugType,lld::coff::Chunk *> > >::_Tidy C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector:1763:0
#33 0x00007ff6618543f1 std::vector<std::pair<llvm::COFF::DebugType,lld::coff::Chunk *>,std::allocator<std::pair<llvm::COFF::DebugType,lld::coff::Chunk *> > >::~vector C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector:712:0
#34 0x00007ff6618543f1 `anonymous namespace'::Writer::~Writer D:\git\llvm-project\lld\COFF\Writer.cpp:197:0
#35 0x00007ff6618543f1 lld::coff::writeResult(class lld::coff::COFFLinkerContext &) D:\git\llvm-project\lld\COFF\Writer.cpp:308:0
#36 0x00007ff66170c04d lld::coff::LinkerDriver::linkerMain D:\git\llvm-project\lld\COFF\Driver.cpp:2377:0
#37 0x00007ff661701606 lld::commonContext D:\git\llvm-project\lld\Common\CommonLinkerContext.cpp:42:0
#38 0x00007ff661701606 lld::context D:\git\llvm-project\lld\include\lld\Common\CommonLinkerContext.h:52:0
#39 0x00007ff661701606 lld::errorHandler D:\git\llvm-project\lld\Common\ErrorHandler.cpp:54:0
#40 0x00007ff661701606 lld::errorCount D:\git\llvm-project\lld\Common\ErrorHandler.cpp:66:0
#41 0x00007ff661701606 lld::coff::link(class llvm::ArrayRef<char const *>, class llvm::raw_ostream &, class llvm::raw_ostream &, bool, bool) D:\git\llvm-project\lld\COFF\Driver.cpp:82:0
#42 0x00007ff6616b853d lldMain D:\git\llvm-project\lld\tools\lld\lld.cpp:164:0
#43 0x00007ff6616b7a0f main D:\git\llvm-project\lld\tools\lld\lld.cpp:220:0
#44 0x00007ff664c087e8 invoke_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78:0
#45 0x00007ff664c087e8 __scrt_common_main_seh d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
#46 0x00007ff9402c7034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#47 0x00007ff9408c2651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
```

I took a memory snapshot just after the crash (while debugging):
lld-link

And the VMMap snapshot:
[lld-link.zip](https://github.com/microsoft/snmalloc/files/8459742/lld-link.zip)

**As you can see the location 0x2a27c000000 was reserved for 32 MiB, but it seems snmalloc is trying to (over)commit 64 MiB on that range.**

Running the same `unit_test.exe` link with a different LLD that uses either the Windows Heap or rpmalloc works fine. I've tried running a debug build as well, and also activating gflags/appverifier. Nothing comes up.

Chromium is synced at f5bb8bdfe7b1ddb46e08711f1258368ff7159e4b.
LLVM is synced at ffaf667a435bf064553f12c04a3a199263e3fdcb.
snmalloc is synced at f6e9796bbcf481e72c641980c6fad1df5f88958d.

All running into a "x64 Native Tools Command Prompt for VS 2019" shell based on VS 2019 version 16.11.11. WinSDK is 10.0.22000.
I'm running Windows10 version 21H2, on a i9-11950H with 64 GB RAM.

---

### To repro:

Use the following instructions to sync & build Chromium first: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md
I used the following gn arguments:
```
is_component_build = true
enable_nacl = false
```

Ensure that you're using the same Chromium checkout as mine:
```
D:\git\chromium\src>git checkout f5bb8bdfe7b1ddb46e08711f1258368ff7159e4b
```
I had to hack a bit Chrome to use my local WinSDK, I don't think that affects the issue:
```
D:\git\chromium\src>git diff
diff --git a/build/toolchain/win/setup_toolchain.py b/build/toolchain/win/setup_toolchain.py
index 831e36f74e..2f4e06eb4b 100644
--- a/build/toolchain/win/setup_toolchain.py
+++ b/build/toolchain/win/setup_toolchain.py
@@ -175,7 +175,7 @@ def _LoadToolchainEnv(cpu, toolchain_root, sdk_dir, target_store):
     # Explicitly specifying the SDK version to build with to avoid accidentally
     # building with a new and untested SDK. This should stay in sync with the
     # packaged toolchain in build/vs_toolchain.py.
-    args.append('10.0.20348.0')
+    args.append('10.0.22000.0')
     variables = _LoadEnvFromBat(args)
   return _ExtractImportantEnvironment(variables)

diff --git a/media/audio/win/audio_low_latency_input_win.cc b/media/audio/win/audio_low_latency_input_win.cc
index 8390c8113d..510de0d07c 100644
--- a/media/audio/win/audio_low_latency_input_win.cc
+++ b/media/audio/win/audio_low_latency_input_win.cc
@@ -193,6 +193,8 @@ const char* EffectTypeToString(
       return "DynamicRangeCompression";
     case ABI::Windows::Media::Effects::AudioEffectType_FarFieldBeamForming:
       return "FarFieldBeamForming";
+       case ABI::Windows::Media::Effects::AudioEffectType_DeepNoiseSuppression:
+         return "DeepNoise";
   }
   return "Unknown";
 }
```
You can build now with
```
D:\git\chromium\src\out\Default>autoninja
```
Once the build is complete, you may delete `src\out\Default\unit_tests.{exe,pdb}`. Then run `autoninja -d keeprsp -v` to re-link `unit_tests.exe` again. You should be able then to copy the command-line into a .rsp file, such as:

```
D:\git\chromium\src\out\Default>cat __link.rsp
/OUT:./unit_tests.exe /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\15.0.0\lib\windows "-libpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "-libpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "-libpath:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" -libpath:C:\Scoop\global\apps\winsdk\10.0.22000.194\sdk\lib\10.0.22000.0\ucrt\x64 -libpath:C:\Scoop\global\apps\winsdk\10.0.22000.194\sdk\lib\10.0.22000.0\um\x64 /MACHINE:X64  /PDB:./unit_tests.exe.pdb @./unit_tests.exe.rsp
```
You should be able to run the link command on its own:
```
D:\git\chromium\src\out\Default>"D:\git\chromium\src\third_party\llvm-build\Release+Asserts\bin\lld-link.exe" @__link.rsp /time /summary
                                    Summary
--------------------------------------------------------------------------------
          13495 Input OBJ files (expanded from all cmd-line inputs)
              1 PDB type server dependencies
              0 Precomp OBJ dependencies
       93424557 Input type records
     5252172688 Input type records bytes
       10052586 Merged TPI records
        3027580 Merged IPI records
          25396 Output PDB strings
        8160235 Global symbol records
       18759720 Module symbol records
        2655731 Public symbol records

  Input File Reading:            5235 ms ( 29.4%)
  Code Layout:                    979 ms (  5.5%)
  Commit Output File:              51 ms (  0.3%)
  PDB Emission (Cumulative):    10689 ms ( 60.0%)
    Add Objects:                 5505 ms ( 30.9%)
      Global Type Hashing:        374 ms (  2.1%)
      GHash Type Merging:        1396 ms (  7.8%)
      Symbol Merging:            3718 ms ( 20.9%)
    Publics Stream Layout:        806 ms (  4.5%)
    TPI Stream Layout:             41 ms (  0.2%)
    Commit to Disk:              3825 ms ( 21.5%)
--------------------------------------------------
Total Linking Time:             17803 ms (100.0%)
```

Then build a two-stage LLVM with the commit hash above. Here I used rpmalloc on the first stage, you could probably use snmalloc as well. This is only to make the second stage faster.

```
D:\git\llvm-project>git checkout ffaf667a435bf064553f12c04a3a199263e3fdcb
...

D:\git\llvm-project>cat make_llvm.bat
@echo off
set ROOT=D:/git/llvm-project
cd %ROOT%

set OPT=-Wno-non-virtual-dtor -march=native /GS-
set OPTOPT=%OPT% -Xclang -O3 -fstrict-aliasing
set MOREOPT=%OPTOPT% -fwhole-program-vtables -flto=thin
set STAGE1=%ROOT%/stage1
set STAGE2=%ROOT%/stage2

goto %1

:stage1
rmdir /s /q stage1
mkdir stage1 && cd stage1
cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="llvm;clang;lld" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_TARGETS_TO_BUILD=all -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_LINKER=lld-link.exe -DCMAKE_C_FLAGS="%OPT%" -DCMAKE_CXX_FLAGS="%OPT%" -DLLVM_USE_CRT_RELEASE=MT -DLLVM_INTEGRATED_CRT_ALLOC=D:/git/rpmalloc  -DCMAKE_MT=C:/Scoop/global/apps/winsdk/10.0.22000.194/sdk/bin/10.0.22000.0/x64/mt.exe -DLLVM_ENABLE_PDB=ON
cd %ROOT%
goto :EOF

:stage2_rpmalloc
rmdir /s /q stage2_rpmalloc
mkdir stage2_rpmalloc && cd stage2_rpmalloc
cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="clang;lld;llvm" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=%stage1%/bin/clang-cl.exe -DCMAKE_CXX_COMPILER=%stage1%/bin/clang-cl.exe -DCMAKE_LINKER=%stage1%/bin/lld-link.exe -DCMAKE_C_FLAGS="%MOREOPT%" -DCMAKE_CXX_FLAGS="%MOREOPT%" -DLLVM_USE_CRT_RELEASE=MT -DLLVM_INTEGRATED_CRT_ALLOC=D:/git/rpmalloc -DLLVM_ENABLE_LTO=Thin -DCMAKE_MT=C:/Scoop/global/apps/winsdk/10.0.22000.194/sdk/bin/10.0.22000.0/x64/mt.exe -DLLVM_ENABLE_PDB=ON
cd %ROOT%
goto :EOF

:stage2_snmalloc
rmdir /s /q stage2_snmalloc
mkdir stage2_snmalloc && cd stage2_snmalloc
cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS="clang;lld;llvm" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=%stage1%/bin/clang-cl.exe -DCMAKE_CXX_COMPILER=%stage1%/bin/clang-cl.exe -DCMAKE_LINKER=%stage1%/bin/lld-link.exe -DCMAKE_C_FLAGS="%MOREOPT%" -DCMAKE_CXX_FLAGS="%MOREOPT%" -DLLVM_USE_CRT_RELEASE=MT -DLLVM_INTEGRATED_CRT_ALLOC=D:/git/snmalloc -DLLVM_ENABLE_LTO=Thin -DCMAKE_MT=C:/Scoop/global/apps/winsdk/10.0.22000.194/sdk/bin/10.0.22000.0/x64/mt.exe -DLLVM_ENABLE_PDB=ON
cd %ROOT%
goto :EOF
```

A tiny fix needs to be applied -- _is there a better way to integrate snmalloc into LLVM?_:
```
D:\git\llvm-project>git diff
diff --git a/llvm/lib/Support/CMakeLists.txt b/llvm/lib/Support/CMakeLists.txt
index 7cbff3dddbcd..4d9956ba8336 100644
--- a/llvm/lib/Support/CMakeLists.txt
+++ b/llvm/lib/Support/CMakeLists.txt
@@ -90,7 +90,7 @@ if(LLVM_INTEGRATED_CRT_ALLOC)
     add_definitions(-DENABLE_OVERRIDE -DENABLE_PRELOAD)
     set(ALLOCATOR_FILES "${LLVM_INTEGRATED_CRT_ALLOC}/rpmalloc/rpmalloc.c")
   elseif(LLVM_INTEGRATED_CRT_ALLOC MATCHES "snmalloc$")
-    set(ALLOCATOR_FILES "${LLVM_INTEGRATED_CRT_ALLOC}/src/override/malloc.cc" "${LLVM_INTEGRATED_CRT_ALLOC}/src/override/new.cc")
+    set(ALLOCATOR_FILES "${LLVM_INTEGRATED_CRT_ALLOC}/src/snmalloc/override/new.cc")
     set(system_libs ${system_libs} "mincore.lib" "-INCLUDE:malloc")
   elseif(LLVM_INTEGRATED_CRT_ALLOC MATCHES "mimalloc$")
     set(MIMALLOC_LIB "${LLVM_INTEGRATED_CRT_ALLOC}/out/msvc-x64/Release/mimalloc-static.lib")

D:\git\llvm-project>make_llvm.bat stage1
...(output omitted)

D:\git\llvm-project>ninja check-all -C stage1
...(should be successfull)

D:\git\llvm-project>make_llvm.bat stage2_snmalloc
...(output omitted)

D:\git\llvm-project>ninja check-lld -C stage2_snmalloc
...(should be successfull)
```

You can now re-link Chromium `unit_tests.exe` to exercise the error:
```
D:\git\chromium\src\out\Default>D:\git\llvm-project\stage2_snmalloc\bin\lld-link.exe @__link.rsp /summary /time
out of memory: 0x2087c000000 (0x4000000) could not be committed (0x1e7)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

Please let me know if any further information is needed, or if I should try a fix!
Thank you in advance for your time!

### PR DESCRIPTION
**Pull request by mjp41**
Fixes #506

### CODE REVIEW

**Comment by nwf** [comment]
This seems like it's going to prevent a lot of consolidation we don't intend: there are two LargeBuddyRange-s in the alloc path, and the `REFILL_SIZE` of the smaller one is 2M.

**Comment by davidchisnall** [comment]
I'm using the PAL without a PageMap, so I'd prefer to not put it there.  Putting it in `PagemapRegisterRange` looks fine.  

I think part of the problem here is that there are two different concepts of coalescing, at the different levels:

 - `LargeBuddyRange` can coalesce anything on non-CHERI platforms.  On CHERI platforms it can coalesce only things for which it has a capability that spans both ranges.
 - The PAL may not be able to coalesce things that were part of different reservations.

I wonder if we need to deconflate them somewhat.  We want the `LargeBuddyRange` to be able to coalesce anything (in the absence of CHERI) so that we can do large allocations (and avoid the pathological cases of allocating a load of 2 MiB allocations until you run out of address space, free them all, and then try to allocate a 1 GiB object).  We want the PAL to know when it has to do two system calls to free something or change its mapping properties.

**Comment by mjp41** [comment]
OKay, I have added it to `PagemapRegisterRange`, and made that take a template parameter for whether the consolidation should occur, i.e. should it track the start of the incoming `alloc_range`.  This means on Windows and CHERI, we will not consolidate mmap/virtualalloc calls, on other platforms the marker won't be applied and we will consolidate.

This change is show what growing, but I think in the right direction.

**Comment by mjp41** [comment]
@davidchisnall could you check I have maintained the backend invariant sufficiently.

**Pull request merged**
