### PR TITLE
Fix ARM 32 bits build, prfm is a 64 bits instruction.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mjp41** [comment]
Do you know why the ARM 32-bit CI was not failing?  What should we change on that pipeline?

**Comment by devnexen** [comment]
I do not really know azure pipelines, I do not know if the 32 bits build are genuine 32 bits or labels ?
Anyway I was just testing the build on a raspberry.

**Review by davidchisnall — APPROVED** [review]

**Comment by davidchisnall** [comment]
@devnexen, what's the compiler that you're using?  I think we'll probably use `__builtin_prefetch()` with clang and only use this version on gcc Arm.  We might want to expand the CI to try gcc on the Arm builds.

**Comment by devnexen** [comment]
ah right I did not notice but I was using gcc indeed :)

**Comment by mjp41** [comment]
@devexen, thanks for fixing this.

**Pull request merged**
