### PR TITLE
Allowing GlobalState to be extended easier for custom Backend implementations

### PR DESCRIPTION
**Pull request by ihaller**
This change is to enable code reuse when implementing a custom BackendAllocator, by enabling inheritance from it and its GlobalState.
Changes field protection from private to protected within GlobalState and templates the actual type of the Pagemap entries, with a default to MetaEntry.
Valid template arguments for the Pagemap entries should be able to seamlessly convert to and from MetaEntry and have a size that is a power of 2.

### CODE REVIEW

**Comment by nwf** [comment]
How messy would it be to not default the template parameter to `MetaEntry` (which is defined in `src/mem`, not `src/backend`)?

**Comment by ihaller** [comment]
It would only need to be specified in 2 files, both located in `src/mem` and once when people implement a new `CommonConfig`. I am happy to make this change, if people decide that it is the right thing to do.

**Comment by nwf** [comment]
It's probably best left for another PR if it's not trivial.  This one LGTM.

**Review by mjp41 — APPROVED** [review]
LGTM, @davidchisnall?

**Comment by mjp41** [comment]
@nwf the relationship between `src/mem` and `src/backend` is not the cleanest, I am hoping that more eyes will bring clarity.  We might need a `src/core` which contains components the `backend` can depend on.

**Review by davidchisnall — APPROVED** [review]

**Comment by davidchisnall** [comment]
I'm not using `BackendAllocator` at all, but this doesn't conflict with anything that I am using or any of my other changes.

**Pull request merged**
