### PR TITLE
POSIX_COMMIT_CHECKS adding for apple.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mjp41** [comment]
@devnexen thanks for thinking about this.  You also need the equivalent to 

https://github.com/microsoft/snmalloc/blob/master/src/pal/pal_bsd.h#L42-L44

to simulate actually removing the pages from being accessible. This is actually more important than the memset.

**Comment by devnexen** [comment]
Yes I know but unfortunately func-malloc* tests abort with it.

**Comment by mjp41** [comment]
Does it do that if we disable calling the `MADV_FREE_REUSABLE`, when we have the commit checks on?  And remove the converse `MADV_FREE_REUSE` in that mode too?

**Comment by devnexen** [comment]
Unfortunately still does not still work (on Mac M1/ARM it should work on Mac Intel).

**Comment by devnexen** [comment]
I propose doing it only for Mac Intel (it works as expected) if that s fine for you ?

**Comment by devnexen** [comment]
With actual code both work under Mac Intel and ARM

**Review by mjp41 — CHANGES_REQUESTED** [review]
LGTM to me, but Clang format is unhappy
https://dev.azure.com/snmalloc/snmalloc/_build/results?buildId=1308&view=logs&j=fb683405-d979-52da-6de9-2541dff429a6&t=f66a877f-3a0c-5131-ec8c-e97d54dcc0fe

@davidchisnall, any comments?

**Review by mjp41 — APPROVED** [review]

**Pull request merged**
