### PR TITLE
Disable compare-exchange/mxc16  unsupported on android as warning are…

### PR DESCRIPTION
**Pull request by devnexen**
… treated as errors.

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
@devnexen 
what is your `android-ndk` version? It is interesting that it seems that I cannot reproduce the problem with
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/opt/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64
```

**Comment by SchrodingerZhu** [comment]
FYI, I didn't see any problem in my compile commands.

[compile-commands.zip](https://github.com/microsoft/snmalloc/files/4533481/compile-commands.zip)

**Comment by devnexen** [comment]
The very last (21.x) ... in fact there is no so much pb but when warnings as treated as in errors in y case that break the build for unsupported flag.

**Comment by SchrodingerZhu** [comment]
Could u please take a look at my dumped commands and compare with yours?
As it is written in the `CMakeLists.txt`, this flag should be clear for those `arm` targets.
As for `x86_64`, those commands could run without problem on my side. A little bit strange.

My version is also `r21.b-1` which is carrying a clang `9.0.8`.

**Comment by devnexen** [comment]
Ah right I see in my side what went wrong sorry for the noise.

**Comment by mjp41** [comment]
This issue makes me strangely happy: the first PR/Issue that didn't involve an MSFT person. :-)

**Pull request closed without merging**
