### PR TITLE
New option to name reserved pages.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mjp41** [comment]
I really like the idea of this.  I had wondered how this might be possible when looking at dumps of the virtual memory, and trying to work out what was snmalloc.  I couldn't really find much documentation of this feature though.  So I am a bit concerned about compatibility.

**Comment by devnexen** [comment]
yes it is very recent on Linux (5.17) to the point it does not appear in the man page :-) but exists since a while on android and couple of major app like chromium use this ability.

**Comment by mjp41** [comment]
@devnexen, I tried this on a few machines, but none of them had a recent enough kernel.  Nothing went wrong though.  So generally I am happy to add this.  Would you be able to add a comment showing the contents of `/proc/pid/maps` for something using snmalloc?

**Comment by devnexen** [comment]
```
7fa5f0ceb000-7fa5f0e00000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fa5f0e00000-7fa5f1800000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fa5f1800000-7fa5f1c00000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fa5f1c00000-7fa5f1ceb000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fa5f1ceb000-7fa5f1cec000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fa5f1cec000-7fc5db45e000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fc5db45e000-7fc5db477000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fc5db477000-7fc5db48e000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fc5db48e000-7fc5db497000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fc5db497000-7fc5db4ae000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fc5db4ae000-7fc5db4b3000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fc5db4b3000-7fe5f1ceb000 rw-p 00000000 00:00 0                          [anon:snmalloc]
7fe5f1ceb000-7fe5f1cf6000 rw-p 00000000 00:00 0 
7fe5f1cf6000-7fe5f1d04000 r--p 00000000 103:02 8915098                   /usr/lib/x86_64-linux-gnu/libm.so.6
7fe5f1d04000-7fe5f1d80000 r-xp 0000e000 103:02 8915098                   /usr/lib/x86_64-linux-gnu/libm.so.6
7fe5f1d80000-7fe5f1ddb000 r--p 0008a000 103:02 8915098                   /usr/lib/x86_64-linux-gnu/libm.so.6
7fe5f1ddb000-7fe5f1ddc000 r--p 000e4000 103:02 8915098                   /usr/lib/x86_64-linux-gnu/libm.so.6
7fe5f1ddc000-7fe5f1ddd000 rw-p 000e5000 103:02 8915098                   /usr/lib/x86_64-linux-gnu/libm.so.6
```

**Comment by mjp41** [comment]
@devnexen, thanks looks good.   @davidchisnall any concerns on this one?  Otherwise, I'll merge it.

**Comment by davidchisnall** [comment]
Sorry, this got lost in my queue.  It looks fine to me.  It would be nice (in a separate PR, no need to block this one) to pass an `enum` value to `reserve` and `notify_using` with values such as:

 - Unused
 - Allocated
 - Pagemap
 - Metadata

So that these can be tracked separately by the OS on systems that have a mechanism like this.  Possibly with only release builds toggling things between Unused and Allocated states.

**Review by mjp41 — APPROVED** [review]
LGTM

**Pull request merged**
