### PR TITLE
Allow POSIX PALs to overwrite writev and fsync.

### PR DESCRIPTION
**Pull request by davidchisnall**
On FreeBSD (possibly elsewhere) the normal versions of these go via an
indirection layer because they are pthread cancellation points.  This
indirection layer does not work correctly if pthreads can't allocate
memory and so we can't get debug output until malloc is working, at
least a little bit.

With this version, we can call the __sys_ variants, which skip any libc
/ libthr interposition.

### CODE REVIEW

**Review by mjp41 — APPROVED** [review]

**Comment by devnexen** [comment]
would it bother you if I commit to your branch ?

**Comment by mjp41** [comment]
> would it bother you if I commit to your branch ?

@devnexen, I am not sure you will have the ability to directly commit to this branch, but you should be able to PR onto the underlying branch @davidchisnall is using. 

We're always super happy for your contributions ;-)

**Comment by mjp41** [comment]
Or you can use the 
```
```suggestions
```
notation, but that can be painful, and only allows you to change bits that already have changes.

**Comment by devnexen** [comment]
ah I did not notice it was not a fork :)

**Pull request merged**
