### PR TITLE
Catch CI up with github

### PR DESCRIPTION
**Pull request by nwf-msr**
Fallout from https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

### CODE REVIEW

**Review by mjp41 — APPROVED** [review]
LGTM.  If it not to much trouble, could you add a comment about why we aren't using latest. I guess we could evolve some tests to a later clang?

**Comment by nwf-msr** [comment]
No trouble at all.  If you want to pick a `clang` version to switch to, or to add in addition to the `ubuntu-20.04`/`clang-10` mix, I'm happy to add those too.

**Comment by nwf-msr** [comment]
Don't merge; testing newer clangs.  If it works, I'll expand some commentary and then we can merge.

**Comment by nwf-msr** [comment]
OK, maybe ready now. :)

**Review by mjp41 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
