### PR TITLE
fix mingw

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
please wait for test.

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
"unknown conversion type character 'z' in format"

**Comment by SchrodingerZhu** [comment]
@mjp41 sorry, but I suggest revert this commit; since it only partially fixes the problem. I run into some other problems under debug mode.

**Comment by SchrodingerZhu** [comment]
it shows a drawback of not having a pipeline for mingw at the pipeline. Is it possible to add one here?

**Comment by mjp41** [comment]
@SchrodingerZhu if you PR a pipeline, then we will take it.  You can create the PR as draft while you are experimenting, and that should allow you to test CI without emailing everyone for each commit. 

I also suggest you disable all the other pipelines while you are testing to get faster turnaround time. I.e. initially delete all the other pipelines from the azurepipelines.yaml file.

**Pull request merged**
