### PR TITLE
Fix markdown

### PR DESCRIPTION
**Pull request by panekj**

### CODE REVIEW

**Review by mjp41 — APPROVED** [review]
LGTM, thanks for fixing

**Comment by panekj** [comment]
Oops, wrong file

**Comment by panekj** [comment]
There is missing use of `[^mmu-perms]` in `StrictProvenance.md`

**Review by nwf — APPROVED** [review]
Thanks for the fix; the missing `mmu-perms` note looks to have always been detached (oops!).  It should probably go at the end of the sentence "Borrowing terminology from CHERI, we speak of the authority (to a subset of the address space) held by a pointer and will justify actions in terms of this authority.".  If you want to add that, feel free, otherwise I'll track it locally and roll it into a later PR.

**Pull request merged**
