### PR TITLE
OE fixes

### PR DESCRIPTION
**Pull request by mjp41**

### CODE REVIEW

**Comment by mjp41** [comment]
Fixes #155 and #156

**Comment by mjp41** [comment]
@anakrish I believe this should fix the issues you found.  Please could you confirm your happy with this fix for Open Enclave.

**Comment by mjp41** [comment]
CI has passed twice from a manual trigger.  The failure shown of this commit appears to be a failure to acquire a VS2019 VM.

**Comment by anakrish** [comment]
@mjp41 Thanks for fixing these. I confirmed that the fixes work.
Note, even with malloc returning NULL for an unfulfillable allocation, tests/stdc still fails because the allocation failure callback is not invoked. That will work once we formally support pluggable allocators in OE

**Pull request merged**
